export const filterData = [
  {
    title: "시리즈",
    items: ["마리오", "포켓몬", "젤다의 전설", "커비", "동물의 숲"],
  },
  {
    title: "출시년도",
    items: ["2024", "2023", "2022", "2021", "2020"],
  },
];

export const gameData = [
  {
    name: "게임1",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "Game Freak",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임2",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "KONAMI",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임3",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "Nintendo",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임4",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "SEGA",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임5",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "KONAMI",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임6",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "Game Freak",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임7",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "Blizzard",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임8",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "KONAMI",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임9",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "Nintendo",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
];

export const popularProductList = [
  {
    name: "게임1",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임2",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임3",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임4",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
  {
    name: "게임5",
    genre: "",
    release: new Date(),
    price: 50000,
    company: "",
    image: "images/zelda-promo.jpg",
    desc: "",
  },
];
